version: "2.3"

services:
  engine:
    image: qlikcore/engine:12.268.0
    restart: always
    command: -S AcceptEULA=${ACCEPT_EULA}
    ports:
      - "19076:9076"
    volumes: 
      - ./data:/data
    healthcheck:
      test: "exit 0"

  example:
    build: src
    volumes:
      - ./src:/app
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      engine:
        condition: service_healthy
    restart: on-failure
