version: "2.1"

services:
  engine:
    image: qlikcore/engine:12.268.0
    restart: always
    command: -S AcceptEULA=yes
    ports:
      - "19076:9076"
    volumes: 
      - myappvol:/data
    healthcheck:
      test: "exit 0"

  example:
    build: src
    # volumes:
    #   - ./src:/app
    ports:
      - "8081:8080"
    depends_on:
      engine:
        condition: service_healthy
    restart: on-failure

volumes:
  myappvol: {}